### PR TITLE
Popup

### PR DESCRIPTION
**Pull request by kakarrot92**
Style changes for popup card

### CODE REVIEW

**Review by bimbolabuari — CHANGES_REQUESTED** [review]
Hi @kakarrot92  🙂,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 

You have submitted a project, that has no Pull Request description, Kindly add what changes were made on the feature branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

--------

_Reviewed by  @bimbolabuari_

**Comment by hiromataba** [comment]
- You need to add a description to your PR

**Review by hiromataba — CHANGES_REQUESTED** [review]
Hi @kakarrot92 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by bimbolabuari** [comment]
To the next code reviewer 👍 

Kindly approve this project, I have checked all requirements for the modal popup in the @kakarrot92 project.

Thanks

**Review by D4nielJ — APPROVED** [review]
## Hello @kakarrot92, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights 🔥 
- Your modal works perfectly.
- Your UI is really good!
- Good job passing all of the linters.

## Optional suggestions
I would also consider:
- Hiding the overflow on the body of the page when the modal is open. That way users can't scroll through the page when the pop-up is on place. This leads to better UX.
- Using `cursor: pointer` for the X icon on the pop-up.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
